# Introduction to Python
## This is practice Notebook





In [6]:
print ("I'm new to Python")

I'm new to Python


In [9]:
name = input("what is your name:")

what is your name: Arun


In [80]:
print("your age is ", name)
print(len(name))

your age is  Arun
4


In [12]:
print("     ^      ")
print("    / \     ")
print("   / ^ \    ")
print("  /  ^  \   ")
print(" /   ^   \  ")

     ^      
    / \     
   / ^ \    
  /  ^  \   
 /   ^   \  


In [15]:
print ("Arun "* 5)

Arun Arun Arun Arun Arun 


In [17]:
var = 100
print(var*var)

10000


In [35]:
Var1 = Varma
print(Var1)
print(type(Var1))

NameError: name 'Varma' is not defined

In [21]:
pet_name = input("enter your pet name : ")
print("pet name :", pet_name)

enter your pet name :  Rocky


pet name : Rocky


In [32]:
#print the age in the months
in_age  = input("what is your age")
age = int(in_age)
print("you are ", age*12, " Months old")
type(in_age)
type(age)
print(type(in_age))

what is your age 2


you are  24  Months old
<class 'str'>


In [40]:
a=10
b=3

In [42]:
print ("a+b", a+b)
print ("a-b", a-b)
print ("a*b", a*b)
print ("a/b", a/b)
print ("a//b", a//b)
print ("a%b", a%b)
print ("a**b", a**b)


a+b 13
a-b 7
a*b 30
a/b 3.3333333333333335
a//b 3
a%b 1
a**b 1000


In [50]:
print(4+64-3**2%1)

68


In [59]:
x = 3
y = 2.5
z = 5
print(x + y / z)

3.5


In [53]:
print(4 % (1 + 9)**2 - 60 // (7 + 2))

-2


In [67]:
#sting operation
statemnet = "I love Python programming"

print(statemnet[7:13])
print(statemnet[7:12])
print(statemnet[-18:-12])

Python
Pytho
Python


In [68]:
#Let's try building a system that could ask for flavour, and the type of desert user wants
flavour=input("What flavour would you like ")
dessert_type=input("What type of dessert would you like ")
print("You have ordered", flavour+"-"+dessert_type)

What flavour would you like  vanilla
What type of dessert would you like  black_current


You have ordered vanilla-black_current


In [101]:
import ast,sys
input_str = input("please enter the string:")
#Type your code here
i = 0 
message1 = ""
message2 = ""
for i in range(len(input_str)):
    if i % 2 == 0:
        if input_str[i] != '#':
         message1 = message1 + input_str[i]
    elif i % 2 == 1:
        if input_str[i] != '#':
         message2 = message2 + input_str[i]
print(message1+','+message2)

please enter the string: axb#z#


abz,x


In [9]:
#list

L = ['Pythons syntax is easy to learn', 'Pythons syntax is very clear'] 

output_string = L[0] + ' & ' + L[1] 
print(output_string)

#split the string

str1 = "Kumar_Ravi_003"

L1 = str1.split('_')

print(L1[1])
print(L1[0])
print(L1[2])



Pythons syntax is easy to learn & Pythons syntax is very clear
Ravi
Kumar
003


In [12]:
#tuple

x =(1,2,3) 
x[2] = 5
print(x)

TypeError: 'tuple' object does not support item assignment

In [29]:
#tuple
t = (1, 2, 4, 3)
print(t[4])
print(t[2:5])

IndexError: tuple index out of range

In [34]:
x =  (Hello,'2','3')
type(x)

NameError: name 'Hello' is not defined

In [43]:
#tuple add an element

input_tuple = ('Monty Python', 'British', 1969)
add = ('Python',)

new_t = tuple(input_tuple[0:] +  add[0:])
type(new_t)
print(new_t)

('Monty Python', 'British', 1969, 'Python')


In [ ]:
#sets

#return the common elements in the list

A = [5, 1, 3, 4, 4, 5, 6, 7]

B = [3, 3, 5, 5, 1 ,7 ,2]

s_A = set(A)
s_B = set(B)

common = s_A & s_B
result = list(common)
print(result)


In [55]:
nums = set([1,1,2,3,3,3,4,5])
print(len(nums))

5


In [72]:
#Dictionary

input_dict = { 102:['Shiva', 24, 'Content Strategist'],104:['Udit',25,'Content Strategist'], 105:['Huzefa',32,'Project Manager' ]}


emp = input_dict[104][2]
emp
print(emp)

Content Strategist


In [107]:
d = {'Name': 'Monty', 'Profession': 'Singer' }

if "Name" in d:
    print("fouund")   
else:
    print("not found")

fouund


In [103]:
d = {'Name': 'Monty', 'Profession': 'Singer' }

if d.get("Lable") is None:
    answer = 'NA'
    print(answer)
else:
    print("key found")
    
    

NA


In [114]:
input_dict = {'Jack Dorsey' : 'Twitter' , 'Tim Cook' : 'Apple','Jeff Bezos' : 'Amazon' ,'Mukesh Ambani' : 'RJIO'}
sorted(input_dict.values())
print(sorted(input_dict.values()))

['Amazon', 'Apple', 'RJIO', 'Twitter']


In [128]:
dict_1 = {"Python":40, "R":45}
#dict_1.delete('R':45)
#del dict_1['R']
#del dict_1
del dict_1('R':40)
dict_1




SyntaxError: invalid syntax (<ipython-input-128-691ecc7838b7>, line 5)

In [129]:
d = {'Python':40, 'R':45}
print(list(d.keys()))

['Python', 'R']


In [133]:
a=10
b=16
c=20

if( a > b and a > c ):
    print("a")
elif( b > a and b > c):
    print("b")
else:
     print("c")
        

c


In [135]:
#Given the code below, the output obtained in several runs is 'C' 'A' 'D' 'B'.
if score >= 90:
   print('A')
elif score >=80:
   print('B')
elif score >= 70:
   print('C')
elif score >= 60:
   print('D')
else:
   print('F')

NameError: name 'score' is not defined

In [136]:
if (10 < 0) and (0 < -10):
    print("A")
elif (10 > 0) or False:
    print("B")
else:
    print("C")

B


In [138]:
if True or True:
    if False and True or False:
        print('A')
    elif False and False or True and True:
        print('B')
    else:
        print('C')
else:
    print('D')

B


In [142]:
input_str = input("please enter a string")
vowel_list = ['a', 'e', 'i', 'o', 'u']
c = input_str[0]
if c in vowel_list:
    print("YES")
else:
    print("NO")

please enter a string arun


YES


In [155]:
i = 2


for i in range(100,0,-5):
    print(i)

100
95
90
85
80
75
70
65
60
55
50
45
40
35
30
25
20
15
10
5


In [163]:
L1 = [10, 20, 30, 24, 18]
L2 = [8, 14, 15, 20, 10]
L3=[]
for  i in range(len(L2)):
    L3.append(L2(i) - L1(i))
print(L3)

TypeError: 'list' object is not callable

In [224]:
names = ['VARMA', 'raj', 'Gupta', 'SaNdeeP']


new_names = []
for i in range(len(names)):
    names[i] = names[i].title()
    print(names[i])
    


Varma
Raj
Gupta
Sandeep


In [262]:
#print prime number of N

n = int(input("Enter the valude for N:"))
for i in range(1,n):  # 0,1,2,3,4.... N
    flag = True
  # print("iter: ",i)
    for j in range(2,i):   # [2],[3]...[n]
         if i % j == 0:
                #not a prime number
                flag = False
                print(i ," is divisible by ", j)
                break
#    print(flag)

    if flag == True:
        print(i)
    
         

Enter the valude for N: 10


1
2
3
4  is divisible by  2
5
6  is divisible by  2
7
8  is divisible by  2
9  is divisible by  3


In [270]:
l = []
for i in range(-100, 0):
    if(i % 2 == 0):
        l.append(i)
l

[-100,
 -98,
 -96,
 -94,
 -92,
 -90,
 -88,
 -86,
 -84,
 -82,
 -80,
 -78,
 -76,
 -74,
 -72,
 -70,
 -68,
 -66,
 -64,
 -62,
 -60,
 -58,
 -56,
 -54,
 -52,
 -50,
 -48,
 -46,
 -44,
 -42,
 -40,
 -38,
 -36,
 -34,
 -32,
 -30,
 -28,
 -26,
 -24,
 -22,
 -20,
 -18,
 -16,
 -14,
 -12,
 -10,
 -8,
 -6,
 -4,
 -2]

In [271]:
d = {0: 'Fish', 1: 'Bird', 2: 'Mammal'}
for i in d:
    print(i)

0
1
2


In [ ]:
#create a list of n using comprehension Squaer

In [273]:
n = int(input("enter value for N:"))
l1 = [val*val for val in range(1,n)] 
l1

enter value for N: 10


[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [276]:
input_list=['wood','old','apple','big','item','euphoria']

output_list = [word for word in input_list if word[0] in "aeiou"]
output_list

['old', 'apple', 'item', 'euphoria']

In [277]:
d = {x.upper(): x*3 for x in 'acbd'}
print(d)

{'A': 'aaa', 'C': 'ccc', 'B': 'bbb', 'D': 'ddd'}


In [278]:
def func(x, y = 1):
    z = x * y + x + y
    return z

func(2, func(3))


23

In [279]:
def func(x = 1 ,y = 2):
    z = x * y + x + y
    return z

func(2, func(3))

35

In [280]:
min = (lambda x, y: x if x < y else y)
min(101*99, 102*98)

9996

In [287]:
l = ['Santa Cruz','Santa fe','Mumbai','Delhi']

f = lambda x: x if x[0] == 'S'

l1 = filter(f(l),l)
list(l1)

SyntaxError: invalid syntax (<ipython-input-287-c6eddb742edd>, line 3)

In [363]:
l = ['soap','sharp','shy','silent','ship','summer','sheep']
f = lambda x: x[0] == 's'
last = lambda x: x[-1] == 'p'
res = list(filter(f, l))
list(res)
res_last = list(filter(last, res))
list(res_last)


['soap', 'sharp', 'ship', 'sheep']

In [351]:
name1 = ['Ankur', 'Avik', 'Kiran', 'Nitin']
name2 = ['Narang', 'Sarkar', 'R', 'Sareen']

f = lambda x,y: x + ' ' + y 

list(map(f,name1, name2))


['Ankur Narang', 'Avik Sarkar', 'Kiran R', 'Nitin Sareen']

In [352]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

f = lambda x: x % 5 == 0

list(filter(f, l))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [391]:
from functools import reduce
input_list = ['All','you','have','to','fear','is','fear','itself']
reduce(lambda x,y: x+' '+y, input_list)


'All you have to fear is fear itself'

In [392]:
input_list = [65,76,87,23,12,90,99]

reduce(lambda x,y:x if x>y else y, input_list)

99

In [413]:
input_str = "bmaunmdbraai#n#b"
message1 = input_str[0::2]
print(message1)
new = message1.strip('#')
print(new)
message2 = input_str[1::2]
print(message2)
print(message1.strip('#')+','+message2.strip('#'))

bandra##
bandra
mumbainb
bandra,mumbainb


In [430]:
class Student:
    standard = 'IV'
    def __init__(self,age,name,Cid):
        self.age = age
        self.name = name
        self.id = Cid
        
    
student1 = Student(12,"Raj",24)
student1 = Student(12,"Sam",10)
student1 = Student("Shiv",4, 3)
print(student1.name, student1.age, student1.id)
student1.standard = 'VI'
print(student1.standard)

4 Shiv 3
VI


In [433]:
class A :
    x = 10
    def __init__(self, y,z):
        self.y = y
        self.z = z
           
    def update_y(self):
        self.y = self.y * self.z

        
        
A1 = A(3,4)
A2 = A(5,6)

A.x = 30
A1.y + A2.x

33

In [435]:
array_1 = [,2,3,5,4,6,7,8,5,3,21]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


In [460]:
#take input here
import ast 

input_list=ast.literal_eval(input())

m=int(input("m"))
n=int(input("n"))

import numpy as np

array_1 = np.array(input_list)

final_array = array_1 [m < array_1]
final_array = final_array [final_array < n]

print(final_array)

KeyboardInterrupt: Interrupted by user

In [494]:
import numpy as np
l = [[11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34]]

a = np.array(l)

rows = len(a) - 1
cols = len(a[0]) -1 
print(rows, ' ', cols)

col_first = a[:,0]
row_first = a[0,:]
col_last = a[:,cols]
row_last = a[rows,:]
print(col_first)
print(row_first)
print(col_last)
print(row_last)


2   3
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [470]:
print(a[:0])

[]


In [481]:
a = np.zeros((4,4), dtype = int)
print(a)
a[:,0] = 1
a[0,:] = 1
a[:,3] = 1
a[3,:] = 1
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [502]:
a = np.arange(100).reshape(10,10)
print(a)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [523]:
p = [[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [525]:
array_1 = np.arange(21)
#print(array_1)
#print(array_1.reshape(5, 4)[array_1%2 != 0])
#print(array_1[array_1%2 != 0])
#print(array_1[array_1%2 == 0].reshape(5, 2))

print(array_1[array_1%2 != 0].reshape(5, 2))
array_1.transpose()

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [589]:

a1 = np.array([[7, 13, 14],[18, 10, 17],[11, 12, 19]])
a2 = np.array([16, 6, 1])
a3 = np.array([[5, 8, 4, 3]])
a3_t = np.reshape(-1,a3)

a1 = np.vstack((a1, a2))
a1 = np.hstack((a1, a3_t))

print(a1)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [604]:
a1 = np.array([[7, 13, 14],[18, 10, 17],[11, 12, 19]])
a2 = np.array([16, 6, 1])
a3 = np.array([[5, 8, 4, 3]])
a3 = np.transpose(a3)
a1 = np.vstack((a1, a2))
a1 = np.hstack((a1,a3))
print(a1)

[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [602]:
[[7, 13, 14],
[18, 10, 17],
[11, 12, 19]]


array([[5],
       [8],
       [4],
       [3]])

In [609]:
arr = np.array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])
print(np.amax(arr))
result = np.where(arr == np.amax(arr))
print(result)
result = np.where(arr == 12)
print(result)

17
(array([ 6, 13]),)
(array([1, 9]),)


In [89]:
# pandas

# All imports
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv'
# Provide your answer below

df = pd.read_csv('marks_1.csv', header = None, sep = '|')
list_of_columns = ['SL No', 'Name', 'Subject', 'Marks Maximum', 'Marks Obtained', 'Percentage']
df.set_index
df.columns = list_of_columns
df.index.name = "index"
print(df)

print("===========================")
#print(df.loc[[2], ["S.No.", "Name", "Subject", "Percentage"]])
print(df.loc[[3], ["Name", "Subject", "Percentage"]])
print(df.iloc[[3], [0, 1, 4]])
#print(df.iloc[[2], [0, 1, 4]])
#print(df.loc[[2], [0, 1, 4]])


       SL No     Name      Subject  Marks Maximum  Marks Obtained  Percentage
index                                                                        
0          1   Akshay  Mathematics             50              40          80
1          2   Mahima      English             40              33          83
2          3    Vikas  Mathematics             50              42          84
3          4  Abhinav      English             40              31          78
4          5   Mahima      Science             50              40          80
5          6   Akshay      Science             50              49          98
6          7  Abhinav  Mathematics             50              47          94
7          8    Vikas      Science             50              40          80
8          9  Abhinav      Science             50              47          94
9         10    Vikas      English             40              39          98
10        11   Akshay      English             40              3

In [152]:
import numpy as np
import pandas as pd
    
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv')
#print (df)
df.set_index(['Office', 'Department'], inplace=True)
print (df)
#df.sort_index(inplace=True)
#print(df.head())

print(df.info())
print(df.describe())
print(df.shape)
print(df.columns)


                         ID  Rating
Office    Department               
New Delhi Finance     U2F26     3.4
          Marketing   U2M61     3.9
          Sales       U1S15     2.8
Mumbai    HR          U1H87     2.1
New Delhi Sales       U1S51     4.6
...                     ...     ...
          Sales       U3S44     4.8
Bangalore Marketing   U2M11     2.5
          Finance     U3F53     3.2
          Sales       U3S46     2.9
New Delhi Sales       U3S28     2.9

[533 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 533 entries, ('New Delhi', 'Finance') to ('New Delhi', 'Sales')
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      533 non-null    object 
 1   Rating  524 non-null    float64
dtypes: float64(1), object(1)
memory usage: 9.8+ KB
None
           Rating
count  524.000000
mean     3.550191
std      0.850430
min      2.100000
25%      2.800000
50%      3.500000
75%      4.300000
max      5.00

In [74]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF',)
df_2 = df[['month', 'day' , 'temp' , 'area']]
print(df_2.head(20))

   month  day  temp  area
0    mar  fri   8.2   0.0
1    oct  tue  18.0   0.0
2    oct  sat  14.6   0.0
3    mar  fri   8.3   0.0
4    mar  sun  11.4   0.0
5    aug  sun  22.2   0.0
6    aug  mon  24.1   0.0
7    aug  mon   8.0   0.0
8    sep  tue  13.1   0.0
9    sep  sat  22.8   0.0
10   sep  sat  17.8   0.0
11   sep  sat  19.3   0.0
12   aug  fri  17.0   0.0
13   sep  mon  21.3   0.0
14   sep  wed  26.4   0.0
15   sep  fri  22.9   0.0
16   mar  sat  15.1   0.0
17   oct  mon  16.7   0.0
18   mar  wed  15.9   0.0
19   apr  sat   9.3   0.0


In [75]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.iloc[1::2]
print(df_2.head(20))

    X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
1   7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
3   8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
5   8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
7   8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
9   7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
11  7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.0
13  6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.0
15  6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.0
17  8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.0
19  6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.0
21  5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.0
23  7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.0
25  7  4   aug  sun  91.4  142.4  601.

In [134]:
# pandas

# All imports
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/A08MajL8qN4rq72EpVJbAP1Rw/marks_1.csv'
# Provide your answer below

df = pd.read_csv('marks_1.csv', header = None, sep = '|', index_col = 0)
list_of_columns = ['Name', 'Subject', 'Marks Maximum', 'Marks Obtained', 'Percentage']
df.columns = list_of_columns
df.index.name = "SL No"
print(df)

print("===========================")
#print(df.loc[[2], ["S.No.", "Name", "Subject", "Percentage"]])
print(df.loc[[3], ["Name", "Subject", "Percentage"]])
print(df.iloc[[3], [0, 1, 4]])
print(df.iloc[[2], [0, 1, 4]])
#print(df.loc[[2], [0, 1, 4]])

          Name      Subject  Marks Maximum  Marks Obtained  Percentage
SL No                                                                 
1       Akshay  Mathematics             50              40          80
2       Mahima      English             40              33          83
3        Vikas  Mathematics             50              42          84
4      Abhinav      English             40              31          78
5       Mahima      Science             50              40          80
6       Akshay      Science             50              49          98
7      Abhinav  Mathematics             50              47          94
8        Vikas      Science             50              40          80
9      Abhinav      Science             50              47          94
10       Vikas      English             40              39          98
11      Akshay      English             40              35          88
12      Mahima  Mathematics             50              43          86
      

In [138]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df[ (df["area"] > 0) & (df["wind"] > 1) & (df["temp"] > 15)]
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
138  9  9   jul  tue  85.8   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36
139  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0  0.43
140  2  5   sep  mon  90.9  126.5  686.5   7.0  21.9  39   1.8   0.0  0.47
141  1  2   aug  wed  95.5   99.9  513.3  13.2  23.3  31   4.5   0.0  0.55
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0  0.61
143  1  2   jul  sat  90.0   51.3  296.3   8.7  16.6  53   5.4   0.0  0.71
144  2  5   aug  wed  95.5   99.9  513.3  13.2  23.8  32   5.4   0.0  0.77
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0  0.90
147  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0  0.96
148  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0  1.07
149  8  6   sep  thu  93.7   80.9  685.2  17.9  23.7  25   4.5   0.0  1.12
150  6  5   jun  fri  92.5   56.4  433.3   7.1  23.2  39   5.4   0.0  1.19
151  9  9   jul  sun  90.

In [182]:
import numpy as np
import pandas as pd

# The file is stored at the following path:
# 'https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv'
df = pd.read_csv('https://media-doselect.s3.amazonaws.com/generic/NMgEjwkAEGGQZBoNYGr9Ld7w0/rating.csv', index_col = 0)

# Provide your answer below

df["Training"] = df["Rating"].apply([lambda x: "Yes" if x < 3.5 else "No"])
print(df)

#Most efficient team

#print(df.loc["Finance"])

who_need_training = df [ df["Training"] == "Yes"]

print(who_need_training)
need_training_in_fin = who_need_training [ who_need_training["Department"] == "Finance"]
print(need_training_in_fin.shape)
need_training_in_mar = who_need_training [ who_need_training["Department"] == "Marketing"]
print(need_training_in_mar.shape)
need_training_in_hr = who_need_training [ who_need_training["Department"] == "HR"]
print(need_training_in_hr.shape)
need_training_in_sales = who_need_training [ who_need_training["Department"] == "Sales"]
print(need_training_in_sales.shape)

for i in ['Finance', 'HR', 'Sales', 'Marketing']:
    print(i, len(who_need_training[(who_need_training['Department'] == i)]) / len(who_need_training[who_need_training['Department'] == i]))
    
#correct Answer
for i in ['Finance', 'HR', 'Sales', 'Marketing']:
    print(i, len(df[(df['Training'] == 'No') & (df['Department'] == i)]) / len(df[df['Department'] == i]))

      Department     Office  Rating Training
ID                                          
U2F26    Finance  New Delhi     3.4      Yes
U2M61  Marketing  New Delhi     3.9       No
U1S15      Sales  New Delhi     2.8      Yes
U1H87         HR     Mumbai     2.1      Yes
U1S51      Sales  New Delhi     4.6       No
...          ...        ...     ...      ...
U3S44      Sales  New Delhi     4.8       No
U2M11  Marketing  Bangalore     2.5      Yes
U3F53    Finance  Bangalore     3.2      Yes
U3S46      Sales  Bangalore     2.9      Yes
U3S28      Sales  New Delhi     2.9      Yes

[533 rows x 4 columns]
      Department     Office  Rating Training
ID                                          
U2F26    Finance  New Delhi     3.4      Yes
U1S15      Sales  New Delhi     2.8      Yes
U1H87         HR     Mumbai     2.1      Yes
U3M44  Marketing  Bangalore     2.1      Yes
U1S75      Sales  Bangalore     3.0      Yes
...          ...        ...     ...      ...
U1S22      Sales  Bangalore    

In [234]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
print(df)
#Type your groupby command here
df_1 = df.groupby(["month","day"]).mean()

print(df_1)
#print(df_1.head(20))
df_1[['rain','wind']].head(20)
#df_1["rain", "wind"]
#['rain', 'wind']

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]
                  X         Y       FFMC         DMC          D

rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000

In [459]:
import numpy as np 
import pandas as pd

# Defining the three dataframes indicating the gold, silver, and bronze medal counts
# of different countries
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                    )
#print(gold, '\n', silver, '\n', bronze)

#Expected output
#         Medals
#Country        
#USA          72
#France       53
#UK           27
#Russia       25
#Germany      20
#keyboard_arrow_up


final = gold.merge(silver, on = "Country", how = "outer")

final = final.merge(bronze, on = "Country", how = "outer")

final["Medals_x"] = final["Medals_x"].add(0, fill_value = 0)

final["Medals_y"] = final["Medals_y"].add(0, fill_value = 0)
final["Medals"] = final["Medals"].add(0, fill_value = 0)


final["Medals"] = final["Medals_x"] + final["Medals_y"] + final["Medals"]



final = final.drop(["Medals_x", "Medals_y"], axis=1)

print(final.sort_values("Medals", ascending=False, ignore_index = True))

final["Medals"].astype(int)

final['Medals'] = final['Medals'].astype('int')
print(final.set_index(["Country"]))
final = final.sort_values("Medals", ascending=False)

print(final)

   Country  Medals
0      USA    72.0
1   France    53.0
2       UK    27.0
3   Russia    25.0
4  Germany    20.0
         Medals
Country        
USA          72
France       53
Russia       25
Germany      20
UK           27
   Country  Medals
0      USA      72
1   France      53
4       UK      27
2   Russia      25
3  Germany      20


In [426]:
import warnings
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context
warnings.simplefilter("ignore")

import pandas as pd
df_1 = pd.read_csv('https://query.data.world/s/vv3snq28bp0TJq2ggCdxGOghEQKPZo')
df_2 = pd.read_csv('https://query.data.world/s/9wVKjNT0yiRc3YbVJaiI8a6HGl2d74')
df_3 =pd.concat([df_1, df_2], axis = 0)
print(df_1.head())#print(df_2.head())
print(df_3.head())

NameError: name 'ing' is not defined

In [481]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Group the data 'df' by 'month' and 'day' and find the mean value for column 'rain' and 'wind' using the pivot table command.

df_1 = df.pivot_table(index = ['month','day'] , values = ['rain', 'wind'], aggfunc = 'mean')

print(df_1.head(20))

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000


In [13]:
import re
def sort_nicely( l ):
    #""" Sort the given list in the way that humans expect."""
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    l.sort( key=alphanum_key )
    print(l)

    
l = ["memtrace_rpd_default_global.22888.0.159","memtrace_rpd_default_global.22888.0.225","memtrace_rpd_default_global.22888.0.60","memtrace_rpd_default_global.22888.0.16","memtrace_rpd_default_global.22888.0.226","memtrace_rpd_default_global.22888.0.61","memtrace_rpd_default_global.22888.0.160","memtrace_rpd_default_global.22888.0.227","memtrace_rpd_default_global.22888.0.62","memtrace_rpd_default_global.22888.0.161","memtrace_rpd_default_global.22888.0.228","memtrace_rpd_default_global.22888.0.63","memtrace_rpd_default_global.22888.0.162","memtrace_rpd_default_global.22888.0.229","memtrace_rpd_default_global.22888.0.64","memtrace_rpd_default_global.22888.0.163","memtrace_rpd_default_global.22888.0.23","memtrace_rpd_default_global.22888.0.65","memtrace_rpd_default_global.22888.0.164","memtrace_rpd_default_global.22888.0.230","memtrace_rpd_default_global.22888.0.66","memtrace_rpd_default_global.22888.0.0","memtrace_rpd_default_global.22888.0.165","memtrace_rpd_default_global.22888.0.231","memtrace_rpd_default_global.22888.0.67","memtrace_rpd_default_global.22888.0.1","memtrace_rpd_default_global.22888.0.166","memtrace_rpd_default_global.22888.0.232","memtrace_rpd_default_global.22888.0.68","memtrace_rpd_default_global.22888.0.10","memtrace_rpd_default_global.22888.0.167","memtrace_rpd_default_global.22888.0.233","memtrace_rpd_default_global.22888.0.69","memtrace_rpd_default_global.22888.0.100","memtrace_rpd_default_global.22888.0.168","memtrace_rpd_default_global.22888.0.234","memtrace_rpd_default_global.22888.0.7","memtrace_rpd_default_global.22888.0.101","memtrace_rpd_default_global.22888.0.169","memtrace_rpd_default_global.22888.0.235","memtrace_rpd_default_global.22888.0.70","memtrace_rpd_default_global.22888.0.102","memtrace_rpd_default_global.22888.0.17","memtrace_rpd_default_global.22888.0.236","memtrace_rpd_default_global.22888.0.71","memtrace_rpd_default_global.22888.0.103","memtrace_rpd_default_global.22888.0.170","memtrace_rpd_default_global.22888.0.237","memtrace_rpd_default_global.22888.0.72","memtrace_rpd_default_global.22888.0.104","memtrace_rpd_default_global.22888.0.171","memtrace_rpd_default_global.22888.0.238","memtrace_rpd_default_global.22888.0.73","memtrace_rpd_default_global.22888.0.105","memtrace_rpd_default_global.22888.0.172","memtrace_rpd_default_global.22888.0.239","memtrace_rpd_default_global.22888.0.74","memtrace_rpd_default_global.22888.0.106","memtrace_rpd_default_global.22888.0.173","memtrace_rpd_default_global.22888.0.24","memtrace_rpd_default_global.22888.0.75","memtrace_rpd_default_global.22888.0.107","memtrace_rpd_default_global.22888.0.174","memtrace_rpd_default_global.22888.0.240","memtrace_rpd_default_global.22888.0.76","memtrace_rpd_default_global.22888.0.108","memtrace_rpd_default_global.22888.0.175","memtrace_rpd_default_global.22888.0.241","memtrace_rpd_default_global.22888.0.77","memtrace_rpd_default_global.22888.0.109","memtrace_rpd_default_global.22888.0.176","memtrace_rpd_default_global.22888.0.242","memtrace_rpd_default_global.22888.0.78","memtrace_rpd_default_global.22888.0.11","memtrace_rpd_default_global.22888.0.177","memtrace_rpd_default_global.22888.0.243","memtrace_rpd_default_global.22888.0.79","memtrace_rpd_default_global.22888.0.110","memtrace_rpd_default_global.22888.0.178","memtrace_rpd_default_global.22888.0.244","memtrace_rpd_default_global.22888.0.8","memtrace_rpd_default_global.22888.0.111","memtrace_rpd_default_global.22888.0.179","memtrace_rpd_default_global.22888.0.245","memtrace_rpd_default_global.22888.0.80","memtrace_rpd_default_global.22888.0.112","memtrace_rpd_default_global.22888.0.18","memtrace_rpd_default_global.22888.0.246","memtrace_rpd_default_global.22888.0.81","memtrace_rpd_default_global.22888.0.113","memtrace_rpd_default_global.22888.0.180","memtrace_rpd_default_global.22888.0.247","memtrace_rpd_default_global.22888.0.82","memtrace_rpd_default_global.22888.0.114","memtrace_rpd_default_global.22888.0.181","memtrace_rpd_default_global.22888.0.248","memtrace_rpd_default_global.22888.0.83","memtrace_rpd_default_global.22888.0.115","memtrace_rpd_default_global.22888.0.182","memtrace_rpd_default_global.22888.0.249","memtrace_rpd_default_global.22888.0.84","memtrace_rpd_default_global.22888.0.116","memtrace_rpd_default_global.22888.0.183","memtrace_rpd_default_global.22888.0.25","memtrace_rpd_default_global.22888.0.85","memtrace_rpd_default_global.22888.0.117","memtrace_rpd_default_global.22888.0.184","memtrace_rpd_default_global.22888.0.250","memtrace_rpd_default_global.22888.0.86","memtrace_rpd_default_global.22888.0.118","memtrace_rpd_default_global.22888.0.185","memtrace_rpd_default_global.22888.0.251","memtrace_rpd_default_global.22888.0.87","memtrace_rpd_default_global.22888.0.119","memtrace_rpd_default_global.22888.0.186","memtrace_rpd_default_global.22888.0.252","memtrace_rpd_default_global.22888.0.88","memtrace_rpd_default_global.22888.0.12","memtrace_rpd_default_global.22888.0.187","memtrace_rpd_default_global.22888.0.253","memtrace_rpd_default_global.22888.0.89","memtrace_rpd_default_global.22888.0.120","memtrace_rpd_default_global.22888.0.188","memtrace_rpd_default_global.22888.0.254","memtrace_rpd_default_global.22888.0.9","memtrace_rpd_default_global.22888.0.121","memtrace_rpd_default_global.22888.0.189","memtrace_rpd_default_global.22888.0.255","memtrace_rpd_default_global.22888.0.90","memtrace_rpd_default_global.22888.0.122","memtrace_rpd_default_global.22888.0.19","memtrace_rpd_default_global.22888.0.256","memtrace_rpd_default_global.22888.0.91","memtrace_rpd_default_global.22888.0.123","memtrace_rpd_default_global.22888.0.190","memtrace_rpd_default_global.22888.0.257","memtrace_rpd_default_global.22888.0.92","memtrace_rpd_default_global.22888.0.124","memtrace_rpd_default_global.22888.0.191","memtrace_rpd_default_global.22888.0.26","memtrace_rpd_default_global.22888.0.93","memtrace_rpd_default_global.22888.0.125","memtrace_rpd_default_global.22888.0.192","memtrace_rpd_default_global.22888.0.27","memtrace_rpd_default_global.22888.0.94","memtrace_rpd_default_global.22888.0.126","memtrace_rpd_default_global.22888.0.193","memtrace_rpd_default_global.22888.0.28","memtrace_rpd_default_global.22888.0.95","memtrace_rpd_default_global.22888.0.127","memtrace_rpd_default_global.22888.0.194","memtrace_rpd_default_global.22888.0.29","memtrace_rpd_default_global.22888.0.96","memtrace_rpd_default_global.22888.0.128","memtrace_rpd_default_global.22888.0.195","memtrace_rpd_default_global.22888.0.3","memtrace_rpd_default_global.22888.0.97","memtrace_rpd_default_global.22888.0.129","memtrace_rpd_default_global.22888.0.196","memtrace_rpd_default_global.22888.0.30","memtrace_rpd_default_global.22888.0.98","memtrace_rpd_default_global.22888.0.13","memtrace_rpd_default_global.22888.0.197","memtrace_rpd_default_global.22888.0.31","memtrace_rpd_default_global.22888.0.99","memtrace_rpd_default_global.22888.0.130","memtrace_rpd_default_global.22888.0.198","memtrace_rpd_default_global.22888.0.32","memtrace_rpd_default_global.22999.0.0","memtrace_rpd_default_global.22888.0.131","memtrace_rpd_default_global.22888.0.199","memtrace_rpd_default_global.22888.0.33","memtrace_rpd_default_global.22999.0.1","memtrace_rpd_default_global.22888.0.132","memtrace_rpd_default_global.22888.0.2","memtrace_rpd_default_global.22888.0.34","memtrace_rpd_default_global.22999.0.2","memtrace_rpd_default_global.22888.0.133","memtrace_rpd_default_global.22888.0.20","memtrace_rpd_default_global.22888.0.35","memtrace_rpd_default_global.22888.0.134","memtrace_rpd_default_global.22888.0.200","memtrace_rpd_default_global.22888.0.36","memtrace_rpd_default_global.22888.0.135","memtrace_rpd_default_global.22888.0.201","memtrace_rpd_default_global.22888.0.37","memtrace_rpd_default_global.22888.0.136","memtrace_rpd_default_global.22888.0.202","memtrace_rpd_default_global.22888.0.38","memtrace_rpd_default_global.22888.0.137","memtrace_rpd_default_global.22888.0.203","memtrace_rpd_default_global.22888.0.39","memtrace_rpd_default_global.22888.0.138","memtrace_rpd_default_global.22888.0.204","memtrace_rpd_default_global.22888.0.4","memtrace_rpd_default_global.22888.0.139","memtrace_rpd_default_global.22888.0.205","memtrace_rpd_default_global.22888.0.40","memtrace_rpd_default_global.22888.0.14","memtrace_rpd_default_global.22888.0.206","memtrace_rpd_default_global.22888.0.41","memtrace_rpd_default_global.22888.0.140","memtrace_rpd_default_global.22888.0.207","memtrace_rpd_default_global.22888.0.42","memtrace_rpd_default_global.22888.0.141","memtrace_rpd_default_global.22888.0.208","memtrace_rpd_default_global.22888.0.43","memtrace_rpd_default_global.22888.0.142","memtrace_rpd_default_global.22888.0.209","memtrace_rpd_default_global.22888.0.44","memtrace_rpd_default_global.22888.0.143","memtrace_rpd_default_global.22888.0.21","memtrace_rpd_default_global.22888.0.45","memtrace_rpd_default_global.22888.0.144","memtrace_rpd_default_global.22888.0.210","memtrace_rpd_default_global.22888.0.46","memtrace_rpd_default_global.22888.0.145","memtrace_rpd_default_global.22888.0.211","memtrace_rpd_default_global.22888.0.47","memtrace_rpd_default_global.22888.0.146","memtrace_rpd_default_global.22888.0.212","memtrace_rpd_default_global.22888.0.48","memtrace_rpd_default_global.22888.0.147","memtrace_rpd_default_global.22888.0.213","memtrace_rpd_default_global.22888.0.49","memtrace_rpd_default_global.22888.0.148","memtrace_rpd_default_global.22888.0.214","memtrace_rpd_default_global.22888.0.5","memtrace_rpd_default_global.22888.0.149","memtrace_rpd_default_global.22888.0.215","memtrace_rpd_default_global.22888.0.50","memtrace_rpd_default_global.22888.0.15","memtrace_rpd_default_global.22888.0.216","memtrace_rpd_default_global.22888.0.51","memtrace_rpd_default_global.22888.0.150","memtrace_rpd_default_global.22888.0.217","memtrace_rpd_default_global.22888.0.52","memtrace_rpd_default_global.22888.0.151","memtrace_rpd_default_global.22888.0.218","memtrace_rpd_default_global.22888.0.53","memtrace_rpd_default_global.22888.0.152",
     "memtrace_rpd_default_global.22888.0.219","memtrace_rpd_default_global.22888.0.54","memtrace_rpd_default_global.22888.0.153","memtrace_rpd_default_global.22888.0.22","memtrace_rpd_default_global.22888.0.55","memtrace_rpd_default_global.22888.0.154","memtrace_rpd_default_global.22888.0.220","memtrace_rpd_default_global.22888.0.56","memtrace_rpd_default_global.22888.0.155","memtrace_rpd_default_global.22888.0.221","memtrace_rpd_default_global.22888.0.57","memtrace_rpd_default_global.22888.0.156","memtrace_rpd_default_global.22888.0.222","memtrace_rpd_default_global.22888.0.58","memtrace_rpd_default_global.22888.0.157","memtrace_rpd_default_global.22888.0.223","memtrace_rpd_default_global.22888.0.59","memtrace_rpd_default_global.22888.0.158","memtrace_rpd_default_global.22888.0.224","memtrace_rpd_default_global.22888.0.6"]
sort_nicely(l)

['memtrace_rpd_default_global.22888.0.0', 'memtrace_rpd_default_global.22888.0.1', 'memtrace_rpd_default_global.22888.0.2', 'memtrace_rpd_default_global.22888.0.3', 'memtrace_rpd_default_global.22888.0.4', 'memtrace_rpd_default_global.22888.0.5', 'memtrace_rpd_default_global.22888.0.6', 'memtrace_rpd_default_global.22888.0.7', 'memtrace_rpd_default_global.22888.0.8', 'memtrace_rpd_default_global.22888.0.9', 'memtrace_rpd_default_global.22888.0.10', 'memtrace_rpd_default_global.22888.0.11', 'memtrace_rpd_default_global.22888.0.12', 'memtrace_rpd_default_global.22888.0.13', 'memtrace_rpd_default_global.22888.0.14', 'memtrace_rpd_default_global.22888.0.15', 'memtrace_rpd_default_global.22888.0.16', 'memtrace_rpd_default_global.22888.0.17', 'memtrace_rpd_default_global.22888.0.18', 'memtrace_rpd_default_global.22888.0.19', 'memtrace_rpd_default_global.22888.0.20', 'memtrace_rpd_default_global.22888.0.21', 'memtrace_rpd_default_global.22888.0.22', 'memtrace_rpd_default_global.22888.0.23', '